openapi: 3.0.0
info:
  title: Drone Flight Operations API
  description: API for accessing data about drones.
  version: 1.0.0

servers:
  - url: http://localhost:5000/api/

paths:
  /drones:
    get:
      summary: Retrieve all drones
      responses:
        "200":
          description: A list of drones
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Drone"
  /connection:
    get:
      summary: Test the database connection
      responses:
        "200":
          description: Connection status message
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Successfully connected to the API

components:
  schemas:
    Drone:
      type: object
      properties:
        BUNO_ID:
          type: string
          description: Unique identifier for the drone
        Drone_Model:
          type: string
          description: Model of the drone
        Manufacturer:
          type: string
          description: Manufacturer of the drone
        Purchase_Date:
          type: string
          format: date
          description: Date the drone was purchased
        Serial:
          type: integer
          description: Serial number of the drone
        Status:
          type: string
          description: Current status of the drone (e.g., Active, Maintenance)
        Status_Code:
          type: string
          description: Status code for the drone (e.g., OK, MAINT)
      example:
        BUNO_ID: DR-001
        Drone_Model: DJI Phantom 4 Pro
        Manufacturer: DJI Innovations
        Purchase_Date: "2022-05-20"
        Serial: "23456"
        Status: Active
        Status_Code: OK
